// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBObe08TH57kVF3VrxCJ76uOCUHpkKtIHc',
    appId: '1:66427527475:web:9c20a0efefa941c1a19e46',
    messagingSenderId: '66427527475',
    projectId: 'mynotes-maaz',
    authDomain: 'mynotes-maaz.firebaseapp.com',
    storageBucket: 'mynotes-maaz.appspot.com',
    measurementId: 'G-FBZJ7PC6SS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs3qRRjElabj0NaPx82sAZzOmddX36jWc',
    appId: '1:66427527475:android:7a9eb111129218a0a19e46',
    messagingSenderId: '66427527475',
    projectId: 'mynotes-maaz',
    storageBucket: 'mynotes-maaz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcpLNCbn1fb_es-Wb7aXhNwCPl-6gBERU',
    appId: '1:66427527475:ios:6e89c9900c8d3a55a19e46',
    messagingSenderId: '66427527475',
    projectId: 'mynotes-maaz',
    storageBucket: 'mynotes-maaz.appspot.com',
    iosClientId: '66427527475-hulb0q8vqshbbjotsnh3i0jqiek3sf1u.apps.googleusercontent.com',
    iosBundleId: 'com.xyz.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcpLNCbn1fb_es-Wb7aXhNwCPl-6gBERU',
    appId: '1:66427527475:ios:6e89c9900c8d3a55a19e46',
    messagingSenderId: '66427527475',
    projectId: 'mynotes-maaz',
    storageBucket: 'mynotes-maaz.appspot.com',
    iosClientId: '66427527475-hulb0q8vqshbbjotsnh3i0jqiek3sf1u.apps.googleusercontent.com',
    iosBundleId: 'com.xyz.mynotes',
  );
}
